services:
  aio:
    networks:
      - reverse-proxy
    labels:
      caddy: zootopia.chat

  app:
    networks:
      - reverse-proxy
    labels:
      caddy: app.zootopia.chat

networks:
  reverse-proxy:
    external: true