services:
  aio:
    image: zootopia-aio
    build:
      context: .
      dockerfile: ZootopiaAio/Dockerfile
    environment:
      KEYCLOAK_AUTHORITY: https://auth.zoot.local/realms/main
      KEYCLOAK_CLIENT_ID: aio-local
      DEV_MODE: true
    labels:
      - dev.orbstack.domains=zoot.local

  app:
    image: zootopia-aio-app
    build:
      context: .
      dockerfile: ZootopiaAio.App/Dockerfile
    labels:
      - dev.orbstack.domains=app.zoot.local