services:
  aio:
    image: ghcr.io/zootopiadiscord/aio:main
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: zoot.tawmy.dev

  app:
    image: ghcr.io/zootopiadiscord/aio/app:main
    networks:
      - reverse-proxy
    labels:
      caddy: app.zoot.tawmy.dev

networks:
  reverse-proxy:
    external: true