services:
  aio:
    image: ghcr.io/zootopiadiscord/aio:feature-sunset
    restart: unless-stopped
    environment:
      BOT_TOKEN:
      INVITE_URL: https://discord.gg/tfXMdhR8bu
    labels:
      caddy.reverse_proxy: "{{upstreams 8080}}"
