services:
  aio:
    image: ghcr.io/zootopiadiscord/aio:feature-app
    networks:
      - reverse-proxy
    labels:
      caddy: zoot.tawmy.dev

  app:
    image: ghcr.io/zootopiadiscord/aio/app:feature-app
    networks:
      - reverse-proxy
    labels:
      caddy: app.zoot.tawmy.dev

networks:
  reverse-proxy:
    external: true