<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AssemblyVersion>0.1.0</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ZootopiaAio.Bot\ZootopiaAio.Bot.csproj"/>
    </ItemGroup>

</Project>
